name: Docs

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!**/.github/workflows/**'

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # https://github.com/mkdocs/mkdocs/issues/2370
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate Docs
        run: |
          pip install mkdocs mkdocs-material Pygments
          ./gradlew dokkaGfmMultiModule --no-configuration-cache
          mv build/dokka/gfmMultiModule docs
          cat README.md > docs/index.md
          mkdocs gh-deploy

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write
