# https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce

name: Release APK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'key/key.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: 'jetpack-key'
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/release/*.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: app/build/outputs/apk/release/*.apk

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write